// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd-2gONG85a_PakcO1MK1ke0SMEirSwaM',
    appId: '1:941227419598:web:6e20ae7924230399d66d9f',
    messagingSenderId: '941227419598',
    projectId: 'rural-cbd75',
    authDomain: 'rural-cbd75.firebaseapp.com',
    storageBucket: 'rural-cbd75.appspot.com',
    measurementId: 'G-80MFWSRCLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Qnk3nuvPq6f41bGB_Y2XgK_P68_tbvA',
    appId: '1:941227419598:android:faf7998cb6a22fbdd66d9f',
    messagingSenderId: '941227419598',
    projectId: 'rural-cbd75',
    storageBucket: 'rural-cbd75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWpEqRQNq3dYBLoZOQ4YRKJj1nCQhEsgc',
    appId: '1:941227419598:ios:11461b56c6776b1dd66d9f',
    messagingSenderId: '941227419598',
    projectId: 'rural-cbd75',
    storageBucket: 'rural-cbd75.appspot.com',
    iosBundleId: 'com.example.agritech',
  );
}
